## 데이터 프레임 구조 변경 및 저장
1. DataFrame에 새로운 컬룸을 추가하거나 원하는 자료형으로 변환하는 등의 조작.
2. DataFrame 객체를 csv, excel 등의 파일로 저장 및 열기

In [17]:
# 데이터 프레임 만들기
import pandas as pd

data = {
    '이름' : ['손흥민', '김민재', '이강인', '황희찬', '류현진', '김병현', '박찬호', '추신수'],
    '학교' : ['축구고', '축구고', '축구고', '축구고', '야구고', '야구고', '야구고', '야구고'],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90]
}

df= pd.DataFrame(data)
df

    이름   학교   국어   영어   수학
0  손흥민  축구고   90   85  100
1  김민재  축구고   40   35   50
2  이강인  축구고   80   75   70
3  황희찬  축구고   40   60   70
4  류현진  야구고   15   20   10
5  김병현  야구고   80  100   95
6  박찬호  야구고   55   65   45
7  추신수  야구고  100   85   90

In [18]:
# 인덱스 변경해보기
df.index=['1번','2번','3번','4번','5번','6번','7번','8번']
df

     이름   학교   국어   영어   수학
1번  손흥민  축구고   90   85  100
2번  김민재  축구고   40   35   50
3번  이강인  축구고   80   75   70
4번  황희찬  축구고   40   60   70
5번  류현진  야구고   15   20   10
6번  김병현  야구고   80  100   95
7번  박찬호  야구고   55   65   45
8번  추신수  야구고  100   85   90

In [19]:
# 인덱스 컬룸에 컬룸명을 설정하기
df.index.name='학생번호'
df

       이름   학교   국어   영어   수학
학생번호
1번    손흥민  축구고   90   85  100
2번    김민재  축구고   40   35   50
3번    이강인  축구고   80   75   70
4번    황희찬  축구고   40   60   70
5번    류현진  야구고   15   20   10
6번    김병현  야구고   80  100   95
7번    박찬호  야구고   55   65   45
8번    추신수  야구고  100   85   90

In [20]:
#굳이 인덱스명을 학생번호로 안해도 될것같아.. 그래서 원래대로 0,1,2... 인덱스를 초기화
df.reset_index()

  학생번호   이름   학교   국어   영어   수학
0   1번  손흥민  축구고   90   85  100
1   2번  김민재  축구고   40   35   50
2   3번  이강인  축구고   80   75   70
3   4번  황희찬  축구고   40   60   70
4   5번  류현진  야구고   15   20   10
5   6번  김병현  야구고   80  100   95
6   7번  박찬호  야구고   55   65   45
7   8번  추신수  야구고  100   85   90

In [21]:
# reset_index()를 하면 기존 인덱스로 쓰던 컬룸들이 데이터용 컬룸으로 변경됨.
# 만약. 이 학생번호가 데이터로서 필요없다면.. reset_index()할때 기존 인덱스용 컬룸들을 제거하도록
df.reset_index(drop=True)

    이름   학교   국어   영어   수학
0  손흥민  축구고   90   85  100
1  김민재  축구고   40   35   50
2  이강인  축구고   80   75   70
3  황희찬  축구고   40   60   70
4  류현진  야구고   15   20   10
5  김병현  야구고   80  100   95
6  박찬호  야구고   55   65   45
7  추신수  야구고  100   85   90

In [22]:
# 위 리셋기능작업을 수행하면 원본 데이터프레임은 그대로이고.
# 변경된 새로운 데이터프레임이 출력되었던 것임
# 그래서 현재 데이터프레임을 출력해보면.. 위 reset_index() 작업이 반영되어 있지 않음
df

       이름   학교   국어   영어   수학
학생번호
1번    손흥민  축구고   90   85  100
2번    김민재  축구고   40   35   50
3번    이강인  축구고   80   75   70
4번    황희찬  축구고   40   60   70
5번    류현진  야구고   15   20   10
6번    김병현  야구고   80  100   95
7번    박찬호  야구고   55   65   45
8번    추신수  야구고  100   85   90

In [23]:
# reset_index()를 수행할때 원본 데이터프레임에 적용되게 하려면...
df.reset_index(drop=True, inplace=True)
df

    이름   학교   국어   영어   수학
0  손흥민  축구고   90   85  100
1  김민재  축구고   40   35   50
2  이강인  축구고   80   75   70
3  황희찬  축구고   40   60   70
4  류현진  야구고   15   20   10
5  김병현  야구고   80  100   95
6  박찬호  야구고   55   65   45
7  추신수  야구고  100   85   90

In [24]:
# 새로운 인덱스를 지정할건데.. 특정 컬룸의 값으로 데이터의 이름을 인덱스명으로 사용하도록 변경
df.set_index('이름', inplace=True)
df

      학교   국어   영어   수학
이름
손흥민  축구고   90   85  100
김민재  축구고   40   35   50
이강인  축구고   80   75   70
황희찬  축구고   40   60   70
류현진  야구고   15   20   10
김병현  야구고   80  100   95
박찬호  야구고   55   65   45
추신수  야구고  100   85   90

In [25]:
# 인덱스명을 기준으로 오름차순 또는 내림차순으로 정렬가능
df.sort_index() # inplace를 사용하지 않으면 원본은 그대로.

      학교   국어   영어   수학
이름
김민재  축구고   40   35   50
김병현  야구고   80  100   95
류현진  야구고   15   20   10
박찬호  야구고   55   65   45
손흥민  축구고   90   85  100
이강인  축구고   80   75   70
추신수  야구고  100   85   90
황희찬  축구고   40   60   70

In [26]:
df.sort_index(ascending=False)

      학교   국어   영어   수학
이름
황희찬  축구고   40   60   70
추신수  야구고  100   85   90
이강인  축구고   80   75   70
손흥민  축구고   90   85  100
박찬호  야구고   55   65   45
류현진  야구고   15   20   10
김병현  야구고   80  100   95
김민재  축구고   40   35   50

In [27]:
# 인덱스를 다시 지정하여 원위치...
df.reset_index(inplace=True)
df

    이름   학교   국어   영어   수학
0  손흥민  축구고   90   85  100
1  김민재  축구고   40   35   50
2  이강인  축구고   80   75   70
3  황희찬  축구고   40   60   70
4  류현진  야구고   15   20   10
5  김병현  야구고   80  100   95
6  박찬호  야구고   55   65   45
7  추신수  야구고  100   85   90

### 새로운 컬룸 추가

In [28]:
# 데이터셋에 평균점수는 저장되어 있지 않음. 분석할때마다 평균계산하지말고.. 학생별 평균컬룸을 만들기
# 데이터프레임 자체에 통으로 평균계산 가능
df.mean()  # error

TypeError: Could not convert ['축구고축구고축구고축구고야구고야구고야구고야구고'] to numeric

In [29]:
# 데이터프레임의 컬룸들 중에서 숫자데이터만 평균을 계산
df[['국어','영어','수학']].mean()

국어    62.500
영어    65.625
수학    66.250
dtype: float64

In [30]:
# 학생별 평균을 구하기 위해 평균계산을 가로방향으로 하도록..
df[['국어','영어','수학']].mean(axis=1)

0    91.666667
1    41.666667
2    75.000000
3    56.666667
4    15.000000
5    91.666667
6    55.000000
7    91.666667
dtype: float64

In [32]:
# 평균값 시리즈를 원래 데이터프레임의 '평균'칸을 새로 만들어 추가
df['평균']= df[['국어','영어','수학']].mean(axis=1)
df

    이름   학교   국어   영어   수학         평균
0  손흥민  축구고   90   85  100  91.666667
1  김민재  축구고   40   35   50  41.666667
2  이강인  축구고   80   75   70  75.000000
3  황희찬  축구고   40   60   70  56.666667
4  류현진  야구고   15   20   10  15.000000
5  김병현  야구고   80  100   95  91.666667
6  박찬호  야구고   55   65   45  55.000000
7  추신수  야구고  100   85   90  91.666667

In [33]:
# 평균을 소수점 2자리까지만 표기
df['평균']= df[['국어','영어','수학']].mean(axis=1).round(2)
df

    이름   학교   국어   영어   수학     평균
0  손흥민  축구고   90   85  100  91.67
1  김민재  축구고   40   35   50  41.67
2  이강인  축구고   80   75   70  75.00
3  황희찬  축구고   40   60   70  56.67
4  류현진  야구고   15   20   10  15.00
5  김병현  야구고   80  100   95  91.67
6  박찬호  야구고   55   65   45  55.00
7  추신수  야구고  100   85   90  91.67

In [39]:
# '총점'컬룸 추가하기
df['총점']= df[['국어','영어','수학']].sum(axis='columns') #axis=1
df

    이름   학교   국어   영어   수학     평균   총점
0  손흥민  축구고   90   85  100  91.67  275
1  김민재  축구고   40   35   50  41.67  125
2  이강인  축구고   80   75   70  75.00  225
3  황희찬  축구고   40   60   70  56.67  170
4  류현진  야구고   15   20   10  15.00   45
5  김병현  야구고   80  100   95  91.67  275
6  박찬호  야구고   55   65   45  55.00  165
7  추신수  야구고  100   85   90  91.67  275

In [40]:
# 컬룸 제거
df.drop(['총점'],axis=1)

    이름   학교   국어   영어   수학     평균
0  손흥민  축구고   90   85  100  91.67
1  김민재  축구고   40   35   50  41.67
2  이강인  축구고   80   75   70  75.00
3  황희찬  축구고   40   60   70  56.67
4  류현진  야구고   15   20   10  15.00
5  김병현  야구고   80  100   95  91.67
6  박찬호  야구고   55   65   45  55.00
7  추신수  야구고  100   85   90  91.67

In [41]:
df

    이름   학교   국어   영어   수학     평균   총점
0  손흥민  축구고   90   85  100  91.67  275
1  김민재  축구고   40   35   50  41.67  125
2  이강인  축구고   80   75   70  75.00  225
3  황희찬  축구고   40   60   70  56.67  170
4  류현진  야구고   15   20   10  15.00   45
5  김병현  야구고   80  100   95  91.67  275
6  박찬호  야구고   55   65   45  55.00  165
7  추신수  야구고  100   85   90  91.67  275

In [42]:
# inplace를 사용하지 않고 기능의 결과를 저장하려면..
df= df.drop(['총점'],axis=1)
df

    이름   학교   국어   영어   수학     평균
0  손흥민  축구고   90   85  100  91.67
1  김민재  축구고   40   35   50  41.67
2  이강인  축구고   80   75   70  75.00
3  황희찬  축구고   40   60   70  56.67
4  류현진  야구고   15   20   10  15.00
5  김병현  야구고   80  100   95  91.67
6  박찬호  야구고   55   65   45  55.00
7  추신수  야구고  100   85   90  91.67

In [43]:
# 데이터 분석을 위하여 열심히 데이터구조를 변경하면서 작업한 결과물을..
# 다음날 되면 모두 잃어버림.. 그럼 이 작업을 또 수행.. 이건 짜증..
# 그래서 최종 데이터프레임을 파일로 저장..

## 파일 저장 및 열기
DataFrame 객체를 csv, excel, pickle 파일 등으로 저장하기

In [45]:
# csv 파일로 저장
df.to_csv('./save_files/score.csv') #폴더는 미리 준비되어있어야 함.
# 엑셀프로그램에서 한글이 깨지면.. encoding 방식을 지정
df.to_csv('./save_files/score.csv', encoding='utf-8')

In [46]:
# 데이터프레임의 인덱스도 같이 저장되는게 싫다면..
df.to_csv('./save_files/score.csv', encoding='utf-8', index=False)

In [47]:
# tsv 파일로 저장
df.to_csv('./save_files/score.tsv', encoding='utf-8', index=False, sep='\t')

In [48]:
# excel 파일로 저장
df.to_excel('./save_files/score.xlsx', index=False)  # excel은 인코딩 지정 안됨

#### 저장한 파일 읽기

In [49]:
df1= pd.read_csv('./save_files/score.csv')
df1

    이름   학교   국어   영어   수학     평균
0  손흥민  축구고   90   85  100  91.67
1  김민재  축구고   40   35   50  41.67
2  이강인  축구고   80   75   70  75.00
3  황희찬  축구고   40   60   70  56.67
4  류현진  야구고   15   20   10  15.00
5  김병현  야구고   80  100   95  91.67
6  박찬호  야구고   55   65   45  55.00
7  추신수  야구고  100   85   90  91.67

In [51]:
df2= pd.read_csv('./save_files/score.csv', skiprows=2) # 상위 2개 줄을 제외하고 불러옴
df2

   김민재  축구고   40   35  50  41.67
0  이강인  축구고   80   75  70  75.00
1  황희찬  축구고   40   60  70  56.67
2  류현진  야구고   15   20  10  15.00
3  김병현  야구고   80  100  95  91.67
4  박찬호  야구고   55   65  45  55.00
5  추신수  야구고  100   85  90  91.67

In [52]:
df3= pd.read_csv('./save_files/score.csv', skiprows=2, header=None) # 상위 2개 줄을 제외하고 불러옴
df3

     0    1    2    3   4      5
0  김민재  축구고   40   35  50  41.67
1  이강인  축구고   80   75  70  75.00
2  황희찬  축구고   40   60  70  56.67
3  류현진  야구고   15   20  10  15.00
4  김병현  야구고   80  100  95  91.67
5  박찬호  야구고   55   65  45  55.00
6  추신수  야구고  100   85  90  91.67

In [54]:
# 엑셀파일 읽기
df4= pd.read_excel('./save_files/score.xlsx', skiprows=[1,3,5], nrows=2, index_col='이름') #1,3,5번줄 제외, 총2개 데이터만, 인덱스는 '이름'칸 사용
df4

      학교  국어  영어  수학     평균
이름
김민재  축구고  40  35  50  41.67
황희찬  축구고  40  60  70  56.67

## Pickle 파일 저장하기
> 파이썬 객체를 그대로 저장해주는 표준모듈

문자열을 저장하는 일반적인 파일입출력과 다르게 피클파일은 객체를 그대로(binary데이터)로 저장할 수 있어서 AI, ML의 학습된 모델(특성값, 가중치)을 저장하는 용도로 많이 사용됨.

In [55]:
#1. 피클로 객체 저장하기 ( dump )
import pickle

# 저장할 파이썬의 데이터 - 어떤 타입이든 저장 가능
person= {'name':'sam', 'age':20, 'hobby':['swimming','running']}

# 피클파일에 딕셔너리를 통으로 저장하기
with open('./save_files/person.pkl', 'wb') as file:
    pickle.dump(person, file)

In [56]:
#2. 저장된 피클파일 읽어오기 ( load )
with open('./save_files/person.pkl', 'rb') as file:
    p= pickle.load(file)

# 불러온 데이터 출력
print(p['name'],p['age'],p['hobby'])

sam 20 ['swimming', 'running']

In [58]:
# 판다스의 데이터프레임도 그대로 피클파일로 저장하고 열기
with open('./save_files/score.pickle', 'wb') as file:
    pickle.dump(df, file)

In [59]:
with open('./save_files/score.pickle', 'rb') as file:
    df_a= pickle.load(file)

df_a

    이름   학교   국어   영어   수학     평균
0  손흥민  축구고   90   85  100  91.67
1  김민재  축구고   40   35   50  41.67
2  이강인  축구고   80   75   70  75.00
3  황희찬  축구고   40   60   70  56.67
4  류현진  야구고   15   20   10  15.00
5  김병현  야구고   80  100   95  91.67
6  박찬호  야구고   55   65   45  55.00
7  추신수  야구고  100   85   90  91.67

In [60]:
# 자주 사용하진 않지만.. 데이터프레임을 json이나 dict로 변환할 수 있음.
score_dict= df.to_dict()
score_dict

{'이름': {0: '손흥민',
  1: '김민재',
  2: '이강인',
  3: '황희찬',
  4: '류현진',
  5: '김병현',
  6: '박찬호',
  7: '추신수'},
 '학교': {0: '축구고',
  1: '축구고',
  2: '축구고',
  3: '축구고',
  4: '야구고',
  5: '야구고',
  6: '야구고',
  7: '야구고'},
 '국어': {0: 90, 1: 40, 2: 80, 3: 40, 4: 15, 5: 80, 6: 55, 7: 100},
 '영어': {0: 85, 1: 35, 2: 75, 3: 60, 4: 20, 5: 100, 6: 65, 7: 85},
 '수학': {0: 100, 1: 50, 2: 70, 3: 70, 4: 10, 5: 95, 6: 45, 7: 90},
 '평균': {0: 91.67,
  1: 41.67,
  2: 75.0,
  3: 56.67,
  4: 15.0,
  5: 91.67,
  6: 55.0,
  7: 91.67}}

In [61]:
score_dict['이름']

{0: '손흥민',
 1: '김민재',
 2: '이강인',
 3: '황희찬',
 4: '류현진',
 5: '김병현',
 6: '박찬호',
 7: '추신수'}

In [62]:
df_json= df.to_json()
df_json

'{"\\uc774\\ub984":{"0":"\\uc190\\ud765\\ubbfc","1":"\\uae40\\ubbfc\\uc7ac","2":"\\uc774\\uac15\\uc778","3":"\\ud669\\ud76c\\ucc2c","4":"\\ub958\\ud604\\uc9c4","5":"\\uae40\\ubcd1\\ud604","6":"\\ubc15\\ucc2c\\ud638","7":"\\ucd94\\uc2e0\\uc218"},"\\ud559\\uad50":{"0":"\\ucd95\\uad6c\\uace0","1":"\\ucd95\\uad6c\\uace0","2":"\\ucd95\\uad6c\\uace0","3":"\\ucd95\\uad6c\\uace0","4":"\\uc57c\\uad6c\\uace0","5":"\\uc57c\\uad6c\\uace0","6":"\\uc57c\\uad6c\\uace0","7":"\\uc57c\\uad6c\\uace0"},"\\uad6d\\uc5b4":{"0":90,"1":40,"2":80,"3":40,"4":15,"5":80,"6":55,"7":100},"\\uc601\\uc5b4":{"0":85,"1":35,"2":75,"3":60,"4":20,"5":100,"6":65,"7":85},"\\uc218\\ud559":{"0":100,"1":50,"2":70,"3":70,"4":10,"5":95,"6":45,"7":90},"\\ud3c9\\uade0":{"0":91.67,"1":41.67,"2":75.0,"3":56.67,"4":15.0,"5":91.67,"6":55.0,"7":91.67}}'

In [63]:
df_json= df.to_json(orient='records', force_ascii=False, indent=2)
df_json

'[\n  {\n    "이름":"손흥민",\n    "학교":"축구고",\n    "국어":90,\n    "영어":85,\n    "수학":100,\n    "평균":91.67\n  },\n  {\n    "이름":"김민재",\n    "학교":"축구고",\n    "국어":40,\n    "영어":35,\n    "수학":50,\n    "평균":41.67\n  },\n  {\n    "이름":"이강인",\n    "학교":"축구고",\n    "국어":80,\n    "영어":75,\n    "수학":70,\n    "평균":75.0\n  },\n  {\n    "이름":"황희찬",\n    "학교":"축구고",\n    "국어":40,\n    "영어":60,\n    "수학":70,\n    "평균":56.67\n  },\n  {\n    "이름":"류현진",\n    "학교":"야구고",\n    "국어":15,\n    "영어":20,\n    "수학":10,\n    "평균":15.0\n  },\n  {\n    "이름":"김병현",\n    "학교":"야구고",\n    "국어":80,\n    "영어":100,\n    "수학":95,\n    "평균":91.67\n  },\n  {\n    "이름":"박찬호",\n    "학교":"야구고",\n    "국어":55,\n    "영어":65,\n    "수학":45,\n    "평균":55.0\n  },\n  {\n    "이름":"추신수",\n    "학교":"야구고",\n    "국어":100,\n    "영어":85,\n    "수학":90,\n    "평균":91.67\n  }\n]'