In [1]:
#특정 컬룸과 행을 선택할때 loc, iloc 말고 인덱스[] 만으로 추출

import pandas as pd

data = {
    '이름' : ['손흥민', '김민재', '이강인', '황의찬', '류현진', '김병현', '박찬호', '추신수'],
    '학교' : ['축구고', '축구고', '축구고', '축구고', '야구고', '야구고', '야구고', '야구고'],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90]
}
df= pd.DataFrame(data)
df

    이름   학교   국어   영어   수학
0  손흥민  축구고   90   85  100
1  김민재  축구고   40   35   50
2  이강인  축구고   80   75   70
3  황의찬  축구고   40   60   70
4  류현진  야구고   15   20   10
5  김병현  야구고   80  100   95
6  박찬호  야구고   55   65   45
7  추신수  야구고  100   85   90

In [2]:
# iloc을 사용하지 않고도 특정 컬룸의 특정행을 추출할 수 있음.
df['국어']

0     90
1     40
2     80
3     40
4     15
5     80
6     55
7    100
Name: 국어, dtype: int64

In [4]:
df['국어'][0] #특정 행 추출

np.int64(90)

In [5]:
df['국어'][2:6] #슬라이싱

2    80
3    40
4    15
5    80
Name: 국어, dtype: int64

In [6]:
# loc, iloc 와 같은 것인가?
# 행의 인덱스명을 변경
df.index= ['a','b','c','d','e','f','g','h']
df

    이름   학교   국어   영어   수학
a  손흥민  축구고   90   85  100
b  김민재  축구고   40   35   50
c  이강인  축구고   80   75   70
d  황의찬  축구고   40   60   70
e  류현진  야구고   15   20   10
f  김병현  야구고   80  100   95
g  박찬호  야구고   55   65   45
h  추신수  야구고  100   85   90

In [21]:
df['국어'][0]  # 0번째 행 추출

C:\Users\mbc\AppData\Local\Temp\ipykernel_12672\3457471050.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['국어'][0]  # 0번째 행 추출

np.int64(90)

In [23]:
df['국어'].iloc[0]

np.int64(90)

In [25]:
df[['국어','수학']].iloc[0]

국어     90
수학    100
Name: a, dtype: int64

In [26]:
# loc[[행],[열]]
# iloc[[행번호],[열번호]]
df.iloc[[0],[0]]

    이름
a  손흥민