## 특정 함수를 정의해서 모든 데이터프레임의 셀들에 일괄적용하기
- for 나 map() 보다 빠르게 대용량 데이터를 처리할 수 있음.

In [1]:
# 학생들의 점수가 있는 데이터셋
# 점수별로 등급(A/B/C)을 계산해서 '등급'컬룸에 추가하고 싶음

import pandas as pd
df= pd.DataFrame({
    'name':['철수','영희','민수'],
    'score':[85, 72, 90]
})
df

  name  score
0   철수     85
1   영희     72
2   민수     90

In [2]:
# score(점수)를 받아 'A','B','C' 등급을 계산하여 리턴해주는 함수 정의하기
def get_grade(score):
    if score>=90:
        return 'A'
    elif score>=80:
        return 'B'
    else:
        return 'C'

# 점수(score)칸의 각 값들에 위 함수를 적용(apply)하여 등급(grade)칸을 새로만들어 추가
df['grade']= df['score'].apply(get_grade)  #함수명 전달... 각 값들마다 함수를 적용해줌
df

  name  score grade
0   철수     85     B
1   영희     72     C
2   민수     90     A

In [3]:
# 사례2] 국어/영어 점수를 합친 총점에 따른 합격 여부를 판단
df= pd.DataFrame({
    'name':['철수','영희','민수'],
    'kor':[80,90,70],
    'eng':[75,85,60],
})
df

  name  kor  eng
0   철수   80   75
1   영희   90   85
2   민수   70   60

In [6]:
# 한줄 row 가로방향으로 데이터를 받아 적용하려면 apply()에 axis=1 을 적용
def pass_fail(row):
    total= row['kor']+row['eng']  #총점계산
    return '합격' if total>=150 else '불합격'

df['result']= df.apply(pass_fail, axis=1)  # 함수의 파라미터를 가로방향(한줄)로 받기
df

  name  kor  eng result
0   철수   80   75     합격
1   영희   90   85     합격
2   민수   70   60    불합격

In [8]:
# [함수를 정의하는 모습(Lambda)을 좀 다르게 하는 사례 실습]
# 사례3: 물류센터 출고 검사(무게 기준 통과여부 결정)
# 상황 설정
# 물류센터에서 출고 전 상품 무게 검사를 한다. 
# 상품 종류별 최소 허용 무게가 다름 
# 실제 측정 무게가 기준 이상이면 통과, 아니면 불합격

import pandas as pd

df = pd.DataFrame({
    'item': ['노트북', '고양이 사료', '강아지 사료', '덤벨'],
    'measured_weight': [1.35, 2.8, 4.5, 9.2],   #측정 무게 kg
    'min_weight': [1.3, 3.0, 4.0, 10.0]         #허용최소 무게 kg
})
df

     item  measured_weight  min_weight
0     노트북             1.35         1.3
1  고양이 사료             2.80         3.0
2  강아지 사료             4.50         4.0
3      덤벨             9.20        10.0

In [9]:
#비교적 연산할 식이 간단하니.. 별도로 함수를 만들지 않고.. apply()를 적용하면서 함수를 정의하기
#'점검결과'컬룸을 만들어 람다함수를 적용한 결과를 저장
df['inspection_result']= df.apply(
    lambda row:'통과' if row['measured_weight']>=row['min_weight'] else '불합격',
    axis=1
)
df

     item  measured_weight  min_weight inspection_result
0     노트북             1.35         1.3                통과
1  고양이 사료             2.80         3.0               불합격
2  강아지 사료             4.50         4.0                통과
3      덤벨             9.20        10.0               불합격