## 데이터 프레임에서 자료형을 인식하는 것은 매우 중요함.
- 연산가능 여부
- 날짜기준 분석
- 버그 예방.  "100"+"20"

In [34]:
# 쇼핑몰 주문 기록(log) 데이터셋을 확인
import pandas as pd
df= pd.read_csv('./data_set/order_log.csv')
df

     주문번호  회원ID    주문금액        주문일자  결제수단
0   10001  u001  12,000  2023-01-05    카드
1   10002  u002   8,500  2023-01-12    카드
2   10003  u003  15,000  2023-01-28    현금
3   10004  u004   3,000  2023-02-02    카드
4   10005  u001  10,000  2023-02-06  계좌이체
5   10006  u002   7,000  2023-02-14    카드
6   10007  u003  12,000  2023-02-26    카드
7   10008  u001   8,500  2023-03-03    카드
8   10009  u004  15,000  2023-03-11    현금
9   10010  u002   3,000  2023-03-19    카드
10  10011  u003  10,000  2023-03-27  계좌이체
11  10012  u001   7,000  2023-04-02    카드
12  10013  u002  12,000  2023-04-06    카드
13  10014  u003   8,500  2023-04-14    카드
14  10015  u004  15,000  2023-04-18    현금
15  10016  u001   3,000  2023-04-25    카드
16  10017  u002  10,000  2023-04-29  계좌이체
17  10018  u003  12,000  2023-05-04    카드
18  10019  u001   8,500  2023-05-09    카드
19  10020  u004  15,000  2023-05-16    현금
20  10021  u002   3,000  2023-05-23    카드
21  10022  u001  10,000  2023-06-02  계좌이체
22  10023  u002   7,000  2023-06-07    카드
23  10024  u003  12,000  2023-06-13    카드
24  10025  u004   8,500  2023-06-18    카드
25  10026  u001  15,000  2023-06-24    현금
26  10027  u002   3,000  2023-06-29    카드
27  10028  u003  12,000  2023-07-03    카드
28  10029  u001   8,500  2023-07-08    카드
29  10030  u002  15,000  2023-07-15    현금
30  10031  u004   3,000  2023-07-21    카드
31  10032  u001  10,000  2023-07-27  계좌이체
32  10033  u002   7,000  2023-08-02    카드
33  10034  u003  12,000  2023-08-06    카드
34  10035  u004   8,500  2023-08-11    카드
35  10036  u001  15,000  2023-08-17    현금
36  10037  u002   3,000  2023-08-22    카드
37  10038  u003  10,000  2023-08-29  계좌이체
38  10039  u001  12,000  2023-09-04    카드
39  10040  u002   8,500  2023-09-10    카드
40  10041  u003  15,000  2023-09-18    현금
41  10042  u004   3,000  2023-09-23    카드
42  10043  u001  10,000  2023-09-28  계좌이체
43  10044  u002   7,000  2023-10-03    카드
44  10045  u003  12,000  2023-10-08    카드
45  10046  u001   8,500  2023-10-14    카드
46  10047  u004  15,000  2023-10-20    현금
47  10048  u002   3,000  2023-10-26    카드
48  10049  u003  10,000  2023-10-31  계좌이체
49  10050  u001  12,000  2023-11-05    카드
50  10051  u002   8,500  2023-11-09    카드
51  10052  u003  15,000  2023-11-16    현금
52  10053  u004   3,000  2023-11-22    카드
53  10054  u001  10,000  2023-11-27  계좌이체
54  10055  u002   7,000  2023-12-02    카드
55  10056  u003  12,000  2023-12-07    카드
56  10057  u004   8,500  2023-12-12    카드
57  10058  u001  15,000  2023-12-18    현금
58  10059  u002   3,000  2023-12-23    카드
59  10060  u003  10,000  2023-12-29  계좌이체

In [35]:
# 주문금액의 평균을 알고싶어..
df['주문금액'].mean()

TypeError: Could not convert string '12,0008,50015,0003,00010,0007,00012,0008,50015,0003,00010,0007,00012,0008,50015,0003,00010,00012,0008,50015,0003,00010,0007,00012,0008,50015,0003,00012,0008,50015,0003,00010,0007,00012,0008,50015,0003,00010,00012,0008,50015,0003,00010,0007,00012,0008,50015,0003,00010,00012,0008,50015,0003,00010,0007,00012,0008,50015,0003,00010,000' to numeric

In [36]:
# 주문금액은 숫자처럼 보이지만.. 숫자데이터 아님
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   주문번호    60 non-null     int64
 1   회원ID    60 non-null     object
 2   주문금액    60 non-null     object
 3   주문일자    60 non-null     object
 4   결제수단    60 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.5+ KB

In [37]:
# 자료형 변환 astype() -- 숫자 사이에 ,가 있어서 그냥은 못바꿈.
df['주문금액']= df['주문금액'].str.replace(',','').astype(int)  # or 'int64'
df['주문금액'].mean()

np.float64(9425.0)

In [38]:
# 주문일자 중 2월 주문내역만 추출...
# 문자열에서 2월 데이터 추출이 불편함.
df['주문일자']= pd.to_datetime(df['주문일자'])
df.dtypes

주문번호             int64
회원ID            object
주문금액             int64
주문일자    datetime64[ns]
결제수단            object
dtype: object

In [39]:
# 2월 데이터만 추출
df[ df['주문일자'].dt.month == 2 ]

    주문번호  회원ID   주문금액       주문일자  결제수단
3  10004  u004   3000 2023-02-02    카드
4  10005  u001  10000 2023-02-06  계좌이체
5  10006  u002   7000 2023-02-14    카드
6  10007  u003  12000 2023-02-26    카드

In [46]:
# 연월까지 모두 필터링 2023년 4월
df[ (df['주문일자'].dt.year==2023) & (df['주문일자'].dt.month==4) ]

     주문번호  회원ID   주문금액       주문일자  결제수단
11  10012  u001   7000 2023-04-02    카드
12  10013  u002  12000 2023-04-06    카드
13  10014  u003   8500 2023-04-14    카드
14  10015  u004  15000 2023-04-18    현금
15  10016  u001   3000 2023-04-25    카드
16  10017  u002  10000 2023-04-29  계좌이체

In [47]:
# 위 and 연산을 보다 쉽게.. 하기 위해 날짜를 인덱스로 사용
df.set_index('주문일자').loc['2023-06'] #인덱스명이 일치하지 않아도 됨.

             주문번호  회원ID   주문금액  결제수단
주문일자
2023-06-02  10022  u001  10000  계좌이체
2023-06-07  10023  u002   7000    카드
2023-06-13  10024  u003  12000    카드
2023-06-18  10025  u004   8500    카드
2023-06-24  10026  u001  15000    현금
2023-06-29  10027  u002   3000    카드

In [48]:
# 결제수단 데이터 유형
df['결제수단'].value_counts()  # 각 값들의 개수

결제수단
카드      39
현금      11
계좌이체    10
Name: count, dtype: int64

In [49]:
# 결제수단 처럼 정해져있는 값을 가진 데이터의 유형을 범주형이라고 부름
df['결제수단'].dtype

dtype('O')

In [50]:
# 문자열로 되어있음.. 메모리를 조금 효율적으로 하고싶다면..
# 범주형의 자료형을 object --> category

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   주문번호    60 non-null     int64
 1   회원ID    60 non-null     object
 2   주문금액    60 non-null     int64
 3   주문일자    60 non-null     datetime64[ns]
 4   결제수단    60 non-null     object
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 2.5+ KB

In [51]:
df['결제수단']= df['결제수단'].astype('category')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   주문번호    60 non-null     int64
 1   회원ID    60 non-null     object
 2   주문금액    60 non-null     int64
 3   주문일자    60 non-null     datetime64[ns]
 4   결제수단    60 non-null     category
dtypes: category(1), datetime64[ns](1), int64(2), object(1)
memory usage: 2.2+ KB

In [53]:
df

     주문번호  회원ID   주문금액       주문일자  결제수단
0   10001  u001  12000 2023-01-05    카드
1   10002  u002   8500 2023-01-12    카드
2   10003  u003  15000 2023-01-28    현금
3   10004  u004   3000 2023-02-02    카드
4   10005  u001  10000 2023-02-06  계좌이체
5   10006  u002   7000 2023-02-14    카드
6   10007  u003  12000 2023-02-26    카드
7   10008  u001   8500 2023-03-03    카드
8   10009  u004  15000 2023-03-11    현금
9   10010  u002   3000 2023-03-19    카드
10  10011  u003  10000 2023-03-27  계좌이체
11  10012  u001   7000 2023-04-02    카드
12  10013  u002  12000 2023-04-06    카드
13  10014  u003   8500 2023-04-14    카드
14  10015  u004  15000 2023-04-18    현금
15  10016  u001   3000 2023-04-25    카드
16  10017  u002  10000 2023-04-29  계좌이체
17  10018  u003  12000 2023-05-04    카드
18  10019  u001   8500 2023-05-09    카드
19  10020  u004  15000 2023-05-16    현금
20  10021  u002   3000 2023-05-23    카드
21  10022  u001  10000 2023-06-02  계좌이체
22  10023  u002   7000 2023-06-07    카드
23  10024  u003  12000 2023-06-13    카드
24  10025  u004   8500 2023-06-18    카드
25  10026  u001  15000 2023-06-24    현금
26  10027  u002   3000 2023-06-29    카드
27  10028  u003  12000 2023-07-03    카드
28  10029  u001   8500 2023-07-08    카드
29  10030  u002  15000 2023-07-15    현금
30  10031  u004   3000 2023-07-21    카드
31  10032  u001  10000 2023-07-27  계좌이체
32  10033  u002   7000 2023-08-02    카드
33  10034  u003  12000 2023-08-06    카드
34  10035  u004   8500 2023-08-11    카드
35  10036  u001  15000 2023-08-17    현금
36  10037  u002   3000 2023-08-22    카드
37  10038  u003  10000 2023-08-29  계좌이체
38  10039  u001  12000 2023-09-04    카드
39  10040  u002   8500 2023-09-10    카드
40  10041  u003  15000 2023-09-18    현금
41  10042  u004   3000 2023-09-23    카드
42  10043  u001  10000 2023-09-28  계좌이체
43  10044  u002   7000 2023-10-03    카드
44  10045  u003  12000 2023-10-08    카드
45  10046  u001   8500 2023-10-14    카드
46  10047  u004  15000 2023-10-20    현금
47  10048  u002   3000 2023-10-26    카드
48  10049  u003  10000 2023-10-31  계좌이체
49  10050  u001  12000 2023-11-05    카드
50  10051  u002   8500 2023-11-09    카드
51  10052  u003  15000 2023-11-16    현금
52  10053  u004   3000 2023-11-22    카드
53  10054  u001  10000 2023-11-27  계좌이체
54  10055  u002   7000 2023-12-02    카드
55  10056  u003  12000 2023-12-07    카드
56  10057  u004   8500 2023-12-12    카드
57  10058  u001  15000 2023-12-18    현금
58  10059  u002   3000 2023-12-23    카드
59  10060  u003  10000 2023-12-29  계좌이체