In [3]:
# 1) pandas, numpy, csv, matplotlib 라이브러리를 불러오시오.
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt

In [4]:
# 2) 타이타닉(titanic) 데이터셋을 불러오시오.
df= pd.read_csv('./data_set/titanic_kor.csv', encoding='cp949')
df

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,객실등급,성인여부,성인남성,선실코드,탑승지명,생존여부,개인탑승자
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [5]:
# 3) 데이터셋에서 처음 3개 행을 출력하시오.
df.head(3)

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,객실등급,성인여부,성인남성,선실코드,탑승지명,생존여부,개인탑승자
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

In [6]:
# 4) 데이터셋의 컬럼 명을 출력하시오.
df.columns

Index(['생존', '등급', '성별', '나이', '형제자매', '부모자녀', '요금', '탑승지코드', '객실등급', '성인여부',
       '성인남성', '선실코드', '탑승지명', '생존여부', '개인탑승자'],
      dtype='object')

In [7]:
# 5) 데이터셋에 대한 통계자료를 출력하시오.
df.describe()

               생존          등급          나이        형제자매        부모자녀          요금
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [8]:
# 6) 데이터셋의 각 컬럼에 대한 데이터 형식(int, object, float...)을 출력하시오
df.dtypes

생존         int64
등급         int64
성별        object
나이       float64
형제자매       int64
부모자녀       int64
요금       float64
탑승지코드     object
객실등급      object
성인여부      object
성인남성        bool
선실코드      object
탑승지명      object
생존여부      object
개인탑승자       bool
dtype: object

In [9]:
# 7) '객실등급' 컬럼과 '요금' 컬럼에 대한 데이터만 출력하시오
df[['객실등급','요금']]

       객실등급       요금
0     Third   7.2500
1     First  71.2833
2     Third   7.9250
3     First  53.1000
4     Third   8.0500
..      ...      ...
886  Second  13.0000
887   First  30.0000
888   Third  23.4500
889   First  30.0000
890   Third   7.7500

[891 rows x 2 columns]

In [10]:
# 8) 인덱스 10 ~ 15번 행에 대한 데이터만 출력하시오
df.loc[10:15]

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,객실등급,성인여부,성인남성,선실코드,탑승지명,생존여부,개인탑승자
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True

In [11]:
# 9) '객실등급' 컬럼과 '요금' 컬럼에 대한 인덱스 21 ~ 23번 행의 데이터만 출력하시오
df.loc[21:23, ['객실등급','요금']]

      객실등급       요금
21  Second  13.0000
22   Third   8.0292
23   First  35.5000

In [12]:
# 10) 객실 요금이 300 불 이상인 데이터에 대한 '성별', '나이', '객실등급', '생존여부' 컬럼을 출력하시오
df.loc[ df['요금']>300, ['성별','나이','객실등급','생존여부']]

         성별    나이   객실등급 생존여부
258  female  35.0  First  yes
679    male  36.0  First  yes
737    male  35.0  First  yes

In [13]:
# 11) '객실등급'의 데이터 값을 모두 소문자로 바꾸고 출력하시오. (First -> first, Second -> second, Third -> third)
df['객실등급']= df['객실등급'].str.lower()
df['객실등급']

0       third
1       first
2       third
3       first
4       third
        ...
886    second
887     first
888     third
889     first
890     third
Name: 객실등급, Length: 891, dtype: object

In [14]:
# 12) '성인여부' 컬럼의 데이터 값 중 man, woman 을 adult 로 바꾸시오.
df['성인여부']= df['성인여부'].replace({'man':'adult', 'woman':'adult'})
df['성인여부']

0      adult
1      adult
2      adult
3      adult
4      adult
       ...
886    adult
887    adult
888    adult
889    adult
890    adult
Name: 성인여부, Length: 891, dtype: object

In [15]:
# 13) 데이터 셋의 각 컬럼에 대한 공백(결측치)의 갯수를 출력하시오.
df.isna().sum()

생존         0
등급         0
성별         0
나이       177
형제자매       0
부모자녀       0
요금         0
탑승지코드      2
객실등급       0
성인여부       0
성인남성       0
선실코드     688
탑승지명       2
생존여부       0
개인탑승자      0
dtype: int64

In [16]:
# 14) 데이터셋에는 총 몇 건의 데이터가 저장되어 있는지 출력하시오(전체 탑승자는 몇 명인가)
print('전체 탑승자 수:',len(df))
print('전체 탑승자 수:',df.shape)
print('전체 탑승자 수:',df.shape[0])

전체 탑승자 수: 891
전체 탑승자 수: (891, 15)
전체 탑승자 수: 891

In [17]:
# 15) '생존여부' 컬럼의 데이터와 비교하여 '생존' 컬럼의 데이터 값이 동일한지를 확인하시오. ('생존' 컬럼의 데이터가 1
# 일때, '생존여부' 컬럼의 데이터가 no 이라면 서로 다른 데이터이다. 해당 데이터가 있는지를 찾으면 된다.)
mismatch= df[(df['생존']==1) & (df['생존여부']=='no')]
mismatch

Empty DataFrame
Columns: [생존, 등급, 성별, 나이, 형제자매, 부모자녀, 요금, 탑승지코드, 객실등급, 성인여부, 성인남성, 선실코드, 탑승지명, 생존여부, 개인탑승자]
Index: []

In [21]:
# 16) '생존' 컬럼과 동일한 값이 저장되어 있는 '생존여부' 컬럼을 삭제하시오. 그리고 '등급' 컬럼과 동일한 값이 저장되어 
# 있는 '객실등급' 컬럼을 삭제하시오
df= df.drop(columns=['생존여부','객실등급'])
df

,생존,등급,성별,나이,형제자매,부모자녀,요금,탑승지코드,성인여부,성인남성,선실코드,탑승지명,개인탑승자
0,0,3,male,22.0,1,0,7.2500,S,adult,True,NaN,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,adult,False,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,adult,False,NaN,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,adult,False,C,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,adult,True,NaN,Southampton,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,adult,True,NaN,Southampton,True
887,1,1,female,19.0,0,0,30.0000,S,adult,False,B,Southampton,True
888,0,3,female,NaN,1,2,23.4500,S,adult,False,NaN,Southampton,False
889,1,1,male,26.0,0,0,30.0000,C,adult,True,C,Cherbourg,True
890,0,3,male,32.0,0,0,7.7500,Q,adult,True,NaN,Queenstown,True

In [ ]:
# 17) '탑승지코드' 컬럼과 '탑승지명' 컬럼 모두에서 데이터 값이 누락되어 있는 행(인덱스)을 찾으시오
df['탑승지코드'].isna() & df['탑승지명'].isna()